# Generated by Django 4.0.5 on 2023-08-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_contractprice_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('male_headcount', models.IntegerField()),
                ('female_headcount', models.IntegerField()),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='clinic.people')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='clinic.people')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clinic.company'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_price', to='clinic.company'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
