# Generated by Django 4.0.5 on 2023-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_company_alter_contract_client_alter_quotation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='management_right_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Middle'), (3, 'Top')], null=True),
        ),
    ]
