# Generated by Django 4.0.5 on 2023-09-04 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_people_add_by_alter_company_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='add_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='people',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
