# Generated by Django 4.0.5 on 2023-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_rename_add_by_people_created_by_people_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AddField(
            model_name='people',
            name='company',
            field=models.ManyToManyField(related_name='contact', to='clinic.company'),
        ),
    ]
