# Generated by Django 4.0.5 on 2023-09-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_company_created_by_company_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='contract',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
