# Generated by Django 4.0.5 on 2023-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='clinic/uploaded_files/'),
        ),
    ]
