# Generated by Django 4.0.5 on 2023-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
