# Generated by Django 4.0.5 on 2023-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_alter_contract_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
