# Generated by Django 4.0.5 on 2023-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_contract_archived_by_contract_archived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
