# Generated by Django 4.0.5 on 2023-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_contract_discount_contract_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
