# Generated by Django 4.0.5 on 2023-10-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_contract_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='clinic.people'),
        ),
    ]
