# Generated by Django 4.0.5 on 2023-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_meetup_meetingagendaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='schedule',
        ),
        migrations.AddField(
            model_name='meetup',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
