# Generated by Django 4.0.5 on 2023-10-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_remove_meetup_schedule_meetup_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='end_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
