# Generated by Django 4.0.5 on 2023-10-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_meetup_end_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
