# Generated by Django 4.0.5 on 2023-12-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_alter_user_management_right_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='company',
        ),
    ]
